# Generated by Django 5.1.3 on 2024-11-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_presente', models.CharField(max_length=100, verbose_name='Nome do Presente')),
                ('foto', models.ImageField(upload_to='presentes', verbose_name='Foto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('importancia', models.IntegerField(verbose_name='Importância')),
                ('reservado', models.BooleanField(default=False)),
            ],
        ),
    ]
