# Generated by Django 5.1.3 on 2024-12-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noivos', '0004_convidados_acompanhantes_confirmados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='noivos.convidados')),
            ],
        ),
    ]
